pipeline:
  name: PMU Harness Lab Go
  identifier: PMU_Harness_Lab_Go
  projectIdentifier: PMU_Harness_Go_Lab
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: obs-gh-paulurfi/goHelloWorldServer/blob/main
        build: <+input>
  stages:
    - stage:
        name: PMU Harness Lab Go
        identifier: PMU_Harness_Lab_Go
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: PMU_Harness_Go_Lab
              namespace: harness-lab-go
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: gcr.io/k8s-minikube/kicbase:v0.0.42
                    shell: Sh
                    command: echo "Hi there, Paul!"
